---

variables:
  DEBIAN_FRONTEND: noninteractive

molecule:
  image: $python
  script:
    - apt-get update -qq
    - apt-get -y -qq install yamllint docker.io
    - pip install --no-cache-dir tox
    - if [ -f tox.ini ] ; then tox ; fi
    - if [ ! -f tox.ini ] ; then pip install -r requirements.yml ; pip install ansible-lint ansible-core ; molecule test ; fi
  rules:
    - if: $CI_COMMIT_REF_NAME == "master"
  parallel:
    matrix:
      - image: "alpine"
        tag: "latest"
        python: ['python:3.9', 'python:3.10']
      - image: "amazonlinux"
        tag: "latest"
        python: ['python:3.9', 'python:3.10']
      - image: "enterpriselinux"
        tag: "latest"
        python: ['python:3.9', 'python:3.10']
      - image: "debian"
        tag: "latest"
        python: ['python:3.9', 'python:3.10']
      - image: "debian"
        tag: "bullseye"
        python: ['python:3.9', 'python:3.10']
      - image: "fedora"
        tag: "39"
        python: ['python:3.9', 'python:3.10']
      - image: "fedora"
        tag: "latest"
        python: ['python:3.9', 'python:3.10']
      - image: "fedora"
        tag: "rawhide"
        python: ['python:3.9', 'python:3.10']
      - image: "ubuntu"
        tag: "latest"
        python: ['python:3.9', 'python:3.10']
      - image: "ubuntu"
        tag: "jammy"
        python: ['python:3.9', 'python:3.10']
      - image: "ubuntu"
        tag: "focal"
        python: ['python:3.9', 'python:3.10']

galaxy:
  script:
    - ansible-galaxy role import --api-key ${GALAXY_API_KEY} robertdebock ${CI_PROJECT_NAME}
  rules:
    - if: $CI_COMMIT_TAG != null
