---
image: "robertdebock/github-action-molecule:6.0.1"

variables:
  PY_COLORS: 1

molecule:
  script:
    - if [ -f tox.ini ] ; then tox ; fi
    - if [ ! -f tox.ini ] ; then molecule test ; fi
  rules:
    - if: $CI_COMMIT_REF_NAME == "master"
  parallel:
    matrix:
      - image: "alpine"
        tag: "latest"
      - image: "amazonlinux"
        tag: "latest"
      - image: "enterpriselinux"
        tag: "8"
      - image: "enterpriselinux"
        tag: "latest"
      - image: "debian"
        tag: "latest"
      - image: "debian"
        tag: "bullseye"
      - image: "fedora"
        tag: "39"
      - image: "fedora"
        tag: "latest"
      - image: "fedora"
        tag: "rawhide"
      - image: "opensuse"
        tag: "latest"
      - image: "ubuntu"
        tag: "latest"
      - image: "ubuntu"
        tag: "jammy"
      - image: "ubuntu"
        tag: "focal"

galaxy:
  script:
    - ansible-galaxy role import --api-key ${GALAXY_API_KEY} robertdebock ${CI_PROJECT_NAME}
  rules:
    - if: $CI_COMMIT_TAG != null
