---
sudo: required
language: python
python:
  - "3.7"
services:
  - docker

env:
  global:
    - BOTO_CONFIG="/dev/null"
    - AWS_REGION="eu-central-1"
  matrix:
    - TEST_DISTRO="alpine_latest" ANSIBLE="stable" TEST_DOCKER_IMAGE="alpine:latest" TEST_DOCKER_COMMAND="sh -c 'while true ; do sleep 1 ; done'"
    - TEST_DISTRO="alpine_latest" ANSIBLE="devel" TEST_DOCKER_IMAGE="alpine:latest" TEST_DOCKER_COMMAND="sh -c 'while true ; do sleep 1 ; done'"
    - TEST_DISTRO="alpine_edge" ANSIBLE="all" TEST_DOCKER_IMAGE="alpine:edge" TEST_DOCKER_COMMAND="sh -c 'while true ; do sleep 1 ; done'"
    - TEST_DISTRO="amazonlinux_latest" ANSIBLE="stable" TEST_DOCKER_IMAGE="amazonlinux:latest"
    - TEST_DISTRO="amazonlinux_latest" ANSIBLE="devel" TEST_DOCKER_IMAGE="amazonlinux:latest"
    - TEST_DISTRO="archlinux_latest" ANSIBLE="stable" TEST_DOCKER_IMAGE="archlinux/base:latest"
    - TEST_DISTRO="archlinux_latest" ANSIBLE="devel" TEST_DOCKER_IMAGE="archlinux/base:latest"
    - TEST_DISTRO="centos_latest" ANSIBLE="stable" TEST_DOCKER_IMAGE="centos:latest" TEST_EC2_AMI="ami-dd3c0f36"
    - TEST_DISTRO="centos_latest" ANSIBLE="devel" TEST_DOCKER_IMAGE="centos:latest"
    - TEST_DISTRO="debian_latest" ANSIBLE="stable" TEST_DOCKER_IMAGE="debian:latest" TEST_EC2_AMI="ami-0ca467408e84df23c" TEST_EC2_ROOT_DEVICE="xvda"
    - TEST_DISTRO="debian_latest" ANSIBLE="devel" TEST_DOCKER_IMAGE="debian:latest"
    - TEST_DISTRO="debian_unstable" ANSIBLE="all" TEST_DOCKER_IMAGE="debian:unstable"
    - TEST_DISTRO="fedora_latest" ANSIBLE="stable" TEST_DOCKER_IMAGE="fedora:latest" TEST_EC2_AMI="ami-0438fc4831b5f576f"
    - TEST_DISTRO="fedora_latest" ANSIBLE="devel" TEST_DOCKER_IMAGE="fedora:latest"
    - TEST_DISTRO="fedora_rawhide" ANSIBLE="all" TEST_DOCKER_IMAGE="fedora:rawhide"
    - TEST_DISTRO="gentoo_latest" ANSIBLE="stable" TEST_DOCKER_IMAGE="gentoo/stage3-amd64:latest"
    - TEST_DISTRO="gentoo_latest" ANSIBLE="devel" TEST_DOCKER_IMAGE="gentoo/stage3-amd64:latest"
    - TEST_DISTRO="kali_latest" ANSIBLE="stable" TEST_DOCKER_IMAGE="kalilinux/kali-linux-docker:latest"
    - TEST_DISTRO="kali_latest" ANSIBLE="devel" TEST_DOCKER_IMAGE="kalilinux/kali-linux-docker:latest"
    - TEST_DISTRO="opensuse_leap" ANSIBLE="stable" TEST_DOCKER_IMAGE="opensuse/leap:latest"
    - TEST_DISTRO="opensuse_leap" ANSIBLE="devel" TEST_DOCKER_IMAGE="opensuse/leap:latest"
    - TEST_DISTRO="opensuse_tumbleweed" ANSIBLE="stable" TEST_DOCKER_IMAGE="opensuse/tumbleweed:latest"
    - TEST_DISTRO="opensuse_tumbleweed" ANSIBLE="devel" TEST_DOCKER_IMAGE="opensuse/tumbleweed:latest"
    - TEST_DISTRO="redhat_latest" ANSIBLE="stable" TEST_DOCKER_IMAGE="registry.access.redhat.com/ubi8/ubi:latest" TEST_EC2_AMI="ami-875042eb"
    - TEST_DISTRO="redhat_latest" ANSIBLE="devel" TEST_DOCKER_IMAGE="registry.access.redhat.com/ubi8/ubi:latest"
    - TEST_DISTRO="ubuntu_latest" ANSIBLE="stable" TEST_DOCKER_IMAGE="ubuntu:latest" TEST_EC2_AMI="ami-0cf8fa6a01bb07363"
    - TEST_DISTRO="ubuntu_latest" ANSIBLE="devel" TEST_DOCKER_IMAGE="ubuntu:latest"
    - TEST_DISTRO="ubuntu-devel" ANSIBLE="all" TEST_DOCKER_IMAGE="ubuntu:devel"

matrix:
  fast_finish: false
  allow_failures:
    - env: TEST_DISTRO="alpine_latest" ANSIBLE="devel" TEST_DOCKER_IMAGE="alpine:latest" TEST_DOCKER_COMMAND="sh -c 'while true ; do sleep 1 ; done'"
    - env: TEST_DISTRO="alpine_edge" ANSIBLE="all" TEST_DOCKER_IMAGE="alpine:edge" TEST_DOCKER_COMMAND="sh -c 'while true ; do sleep 1 ; done'"
    - env: TEST_DISTRO="amazonlinux_latest" ANSIBLE="devel" TEST_DOCKER_IMAGE="amazonlinux:latest"
    - env: TEST_DISTRO="archlinux_latest" ANSIBLE="devel" TEST_DOCKER_IMAGE="archlinux/base:latest"
    - env: TEST_DISTRO="centos_latest" ANSIBLE="devel" TEST_DOCKER_IMAGE="centos:latest"
    - env: TEST_DISTRO="debian_latest" ANSIBLE="devel" TEST_DOCKER_IMAGE="debian:latest"
    - env: TEST_DISTRO="debian_unstable" ANSIBLE="all" TEST_DOCKER_IMAGE="debian:unstable"
    - env: TEST_DISTRO="fedora_latest" ANSIBLE="devel" TEST_DOCKER_IMAGE="fedora:latest"
    - env: TEST_DISTRO="fedora_rawhide" ANSIBLE="all" TEST_DOCKER_IMAGE="fedora:rawhide"
    - env: TEST_DISTRO="gentoo_latest" ANSIBLE="devel" TEST_DOCKER_IMAGE="gentoo/stage3-amd64:latest"
    - env: TEST_DISTRO="kali_latest" ANSIBLE="devel" TEST_DOCKER_IMAGE="kalilinux/kali-linux-docker:latest"
    - env: TEST_DISTRO="opensuse_leap" ANSIBLE="devel" TEST_DOCKER_IMAGE="opensuse/leap:latest"
    - env: TEST_DISTRO="opensuse_tumbleweed" ANSIBLE="devel" TEST_DOCKER_IMAGE="opensuse/tumbleweed:latest"
    - env: TEST_DISTRO="redhat_latest" ANSIBLE="devel" TEST_DOCKER_IMAGE="registry.access.redhat.com/ubi8/ubi:latest"
    - env: TEST_DISTRO="ubuntu_latest" ANSIBLE="devel" TEST_DOCKER_IMAGE="ubuntu:latest"
    - env: TEST_DISTRO="ubuntu_devel" ANSIBLE="all" TEST_DOCKER_IMAGE="ubuntu:devel"

addons:
  apt:
    packages:
      # Hotfix for text coloring
      # https://github.com/travis-ci/travis-ci/issues/7967#issuecomment-424521694
      - expect-dev

cache:
  - pip

before_install:
  - sudo apt-get -qq update

install:
  - pip install --upgrade pip
  - pip install tox-travis

script:
  - unbuffer tox

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
  email: true
