sudo: required
language: python
python:
  - "2.7"
  - "3.6"
services:
  - docker

env:
  global:
    - BOTO_CONFIG="/dev/null"
    - AWS_REGION="eu-central-1"
  matrix:
    - MOLECULE_DISTRO="alpine-latest" ANSIBLE="stable" MOLECULE_DOCKER_IMAGE="alpine:latest" MOLECULE_DOCKER_COMMAND="sh -c 'while true ; do sleep 1 ; done'"
    - MOLECULE_DISTRO="alpine-latest" ANSIBLE="devel" MOLECULE_DOCKER_IMAGE="alpine:latest" MOLECULE_DOCKER_COMMAND="sh -c 'while true ; do sleep 1 ; done'"
    - MOLECULE_DISTRO="alpine-edge" ANSIBLE="all" MOLECULE_DOCKER_IMAGE="alpine:edge" MOLECULE_DOCKER_COMMAND="sh -c 'while true ; do sleep 1 ; done'"
    - MOLECULE_DISTRO="archlinux-latest" ANSIBLE="stable" MOLECULE_DOCKER_IMAGE="archlinux/base:latest"
    - MOLECULE_DISTRO="archlinux-latest" ANSIBLE="devel" MOLECULE_DOCKER_IMAGE="archlinux/base:latest"
    - MOLECULE_DISTRO="centos-latest" ANSIBLE="stable" MOLECULE_DOCKER_IMAGE="centos:latest" MOLECULE_EC2_AMI="ami-dd3c0f36"
    - MOLECULE_DISTRO="centos-latest" ANSIBLE="devel" MOLECULE_DOCKER_IMAGE="centos:latest"
    - MOLECULE_DISTRO="debian-latest" ANSIBLE="stable" MOLECULE_DOCKER_IMAGE="debian:latest" MOLECULE_EC2_AMI="ami-0ca467408e84df23c" MOLECULE_EC2_ROOT_DEVICE="xvda"
    - MOLECULE_DISTRO="debian-latest" ANSIBLE="devel" MOLECULE_DOCKER_IMAGE="debian:latest"
    - MOLECULE_DISTRO="debian-unstable" ANSIBLE="all" MOLECULE_DOCKER_IMAGE="debian:unstable"
    - MOLECULE_DISTRO="fedora-latest" ANSIBLE="stable" MOLECULE_DOCKER_IMAGE="fedora:latest" MOLECULE_EC2_AMI="ami-0f904cfaa69a1c64c"
    - MOLECULE_DISTRO="fedora-latest" ANSIBLE="devel" MOLECULE_DOCKER_IMAGE="fedora:latest"
    - MOLECULE_DISTRO="fedora-rawhide" ANSIBLE="all" MOLECULE_DOCKER_IMAGE="fedora:rawhide"
    - MOLECULE_DISTRO="gentoo-latest" ANSIBLE="stable" MOLECULE_DOCKER_IMAGE="gentoo/stage3-amd64:latest"
    - MOLECULE_DISTRO="gentoo-latest" ANSIBLE="devel" MOLECULE_DOCKER_IMAGE="gentoo/stage3-amd64:latest"
    - MOLECULE_DISTRO="kali-latest" ANSIBLE="stable" MOLECULE_DOCKER_IMAGE="kalilinux/kali-linux-docker:latest"
    - MOLECULE_DISTRO="kali-latest" ANSIBLE="devel" MOLECULE_DOCKER_IMAGE="kalilinux/kali-linux-docker:latest"
    - MOLECULE_DISTRO="opensuse-leap" ANSIBLE="stable" MOLECULE_DOCKER_IMAGE="opensuse/leap:latest"
    - MOLECULE_DISTRO="opensuse-leap" ANSIBLE="devel" MOLECULE_DOCKER_IMAGE="opensuse/leap:latest"
    - MOLECULE_DISTRO="opensuse-tumbleweed" ANSIBLE="stable" MOLECULE_DOCKER_IMAGE="opensuse/tumbleweed:latest"
    - MOLECULE_DISTRO="opensuse-tumbleweed" ANSIBLE="devel" MOLECULE_DOCKER_IMAGE="opensuse/tumbleweed:latest"
    - MOLECULE_DISTRO="ubuntu-latest" ANSIBLE="stable" MOLECULE_DOCKER_IMAGE="ubuntu:latest" MOLECULE_EC2_AMI="ami-0cf8fa6a01bb07363"
    - MOLECULE_DISTRO="ubuntu-latest" ANSIBLE="devel" MOLECULE_DOCKER_IMAGE="ubuntu:latest"
    - MOLECULE_DISTRO="ubuntu-devel" ANSIBLE="all" MOLECULE_DOCKER_IMAGE="ubuntu:devel"

matrix:
  fast_finish: false
  allow_failures:
    - env: MOLECULE_DISTRO="alpine-latest" ANSIBLE="devel" MOLECULE_DOCKER_IMAGE="alpine:latest" MOLECULE_DOCKER_COMMAND="sh -c 'while true ; do sleep 1 ; done'"
    - env: MOLECULE_DISTRO="alpine-edge" ANSIBLE="all" MOLECULE_DOCKER_IMAGE="alpine:edge" MOLECULE_DOCKER_COMMAND="sh -c 'while true ; do sleep 1 ; done'"
    - env: MOLECULE_DISTRO="archlinux-latest" ANSIBLE="devel" MOLECULE_DOCKER_IMAGE="archlinux/base:latest"
    - env: MOLECULE_DISTRO="centos-latest" ANSIBLE="devel" MOLECULE_DOCKER_IMAGE="centos:latest"
    - env: MOLECULE_DISTRO="debian-latest" ANSIBLE="devel" MOLECULE_DOCKER_IMAGE="debian:latest"
    - env: MOLECULE_DISTRO="debian-unstable" ANSIBLE="all" MOLECULE_DOCKER_IMAGE="debian:unstable"
    - env: MOLECULE_DISTRO="fedora-latest" ANSIBLE="devel" MOLECULE_DOCKER_IMAGE="fedora:latest"
    - env: MOLECULE_DISTRO="fedora-rawhide" ANSIBLE="all" MOLECULE_DOCKER_IMAGE="fedora:rawhide"
    - env: MOLECULE_DISTRO="gentoo-latest" ANSIBLE="devel" MOLECULE_DOCKER_IMAGE="gentoo/stage3-amd64:latest"
    - env: MOLECULE_DISTRO="kali-latest" ANSIBLE="devel" MOLECULE_DOCKER_IMAGE="kalilinux/kali-linux-docker:latest"
    - env: MOLECULE_DISTRO="opensuse-leap" ANSIBLE="devel" MOLECULE_DOCKER_IMAGE="opensuse/leap:latest"
    - env: MOLECULE_DISTRO="opensuse-tumbleweed" ANSIBLE="devel" MOLECULE_DOCKER_IMAGE="opensuse/tumbleweed:latest"
    - env: MOLECULE_DISTRO="ubuntu-latest" ANSIBLE="devel" MOLECULE_DOCKER_IMAGE="ubuntu:latest"
    - env: MOLECULE_DISTRO="ubuntu-devel" ANSIBLE="all" MOLECULE_DOCKER_IMAGE="ubuntu:devel"

addons:
  apt:
    packages:
      # Hotfix for text coloring
      # https://github.com/travis-ci/travis-ci/issues/7967#issuecomment-424521694
      - expect-dev

cache:
  - pip

before_install:
  - sudo apt-get -qq update

install:
  - pip install --upgrade pip
  - pip install tox-travis

script:
  - travis_wait unbuffer tox

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
  email: true
