---
sudo: required
language: python
services: docker

env:
  - distro: alpine:3.4
  - distro: alpine:3.5
  - distro: alpine:3.6
  - distro: centos:7
  - distro: centos:6
  - distro: debian:stretch
  - distro: fedora:25
  - distro: fedora:26
  - distro: ubuntu:xenial
  - distro: ubuntu:artful

before_install:
  - docker pull "${distro}"

install:
  - role=$(basename $(pwd) | sed 's/ansible-role-//g')
  - containerid=$(docker container run --detach --volume $(pwd):/etc/ansible/roles/${role} ${distro} sleep 3600)
  - if [[ ${distro} == alpine:* ]] ; then docker exec ${containerid} apk add --update ansible ; fi
  - if [[ ${distro} == centos:6 ]] ; then docker exec ${containerid} yum -y install epel-release ; fi
  - if [[ ${distro} == centos:* ]] ; then docker exec ${containerid} yum -y install ansible ; fi
  - if [[ ${distro} == debian:* ]] ; then docker exec ${containerid} apt-get update ; fi
  - if [[ ${distro} == debian:* ]] ; then docker exec ${containerid} apt-get -y install ansible ; fi
  - if [[ ${distro} == fedora:* ]] ; then docker exec ${containerid} dnf -y install ansible ; fi
  - if [[ ${distro} == opensuse:* ]] ; then docker exec ${containerid} zypper --non-interactive install ansible || echo $? ; fi
  - if [[ ${distro} == ubuntu:* ]] ; then docker exec ${containerid} apt-get update ; fi
  - if [[ ${distro} == ubuntu:* ]] ; then docker exec ${containerid} apt-get -y install ansible ; fi

script:
  - docker exec ${containerid} ansible-playbook --inventory /etc/ansible/roles/${role}/tests/inventory /etc/ansible/roles/${role}/tests/test.yml --syntax-check
  - docker exec ${containerid} ansible-playbook --inventory /etc/ansible/roles/${role}/tests/inventory /etc/ansible/roles/${role}/tests/test.yml --connection=local --become

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
