---

- name: assert | Test bootstrap_wait_for_host
  ansible.builtin.assert:
    that:
      - bootstrap_wait_for_host is defined
      - bootstrap_wait_for_host is boolean
    quiet: true

- name: assert | Test bootstrap_timeout
  ansible.builtin.assert:
    that:
      - bootstrap_timeout is defined
      - bootstrap_timeout is number
      - bootstrap_timeout >= 0
    quiet: true

- name: assert | Test bootstrap_become
  ansible.builtin.assert:
    that:
      - bootstrap_become is defined
      - bootstrap_become is boolean
    quiet: true
