---
#
# Ansible managed
#

name: Ansible Molecule

on:
  push:
    tags_ignore:
      - '*'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: molecule
        uses: robertdebock/molecule-action@1.1.3
        with:
          entrypoint: /usr/local/bin/molecule
          args: lint
  test:
    needs:
      - lint
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        config:
          - image: "amazonlinux"
            tag: "1"
          - image: "amazonlinux"
            tag: "latest"
          - image: "alpine"
            tag: "latest"
          - image: "alpine"
            tag: "edge"
          - image: "debian"
            tag: "latest"
          - image: "debian"
            tag: "unstable"
          - image: "centos"
            tag: "7"
          - image: "centos"
            tag: "latest"
          - image: "fedora"
            tag: "30"
          - image: "fedora"
            tag: "latest"
          - image: "fedora"
            tag: "rawhide"
          - image: "opensuse"
            tag: "latest"
          - image: "ubuntu"
            tag: "latest"
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          path: "${{ github.repository }}"
      - name: disable apparmor for mysql
        run: sudo ln -s /etc/apparmor.d/usr.sbin.mysqld /etc/apparmor.d/disable/
      - name: parse apparmor for mysql
        run: sudo apparmor_parser -R /etc/apparmor.d/usr.sbin.mysqld
      - name: molecule
        uses: robertdebock/molecule-action@1.1.3
        with:
          image: ${{ matrix.config.image }}
          tag: ${{ matrix.config.tag }}
          options: "--parallel all"
        env:
          TOX_PARALLEL_NO_SPINNER: 1
