---
#
# Ansible managed
#

name: Ansible Molecule

on:
  push:
    tags_ignore:
      - '*'
  pull_request:
  schedule:
    - cron: '2 2 2 * *'

jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          path: "${{ github.repository }}"
      - name: molecule
        uses: robertdebock/molecule-action@2.6.8
        with:
          command: lint
  test:
    needs:
      - lint
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        config:
          - image: "amazonlinux"
            tag: "latest"
          - image: "centos"
            tag: "7"
          - image: "centos"
            tag: "latest"
          - image: "debian"
            tag: "latest"
          - image: "debian"
            tag: "bullseye"
          - image: "fedora"
            tag: "32"
          - image: "fedora"
            tag: "latest"
          - image: "fedora"
            tag: "rawhide"
          - image: "opensuse"
            tag: "latest"
          - image: "ubuntu"
            tag: "latest"
          - image: "ubuntu"
            tag: "bionic"
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          path: "${{ github.repository }}"
      - name: disable apparmor for mysql
        run: sudo ln -s /etc/apparmor.d/usr.sbin.mysqld /etc/apparmor.d/disable/
      - name: parse apparmor for mysql
        run: sudo apparmor_parser -R /etc/apparmor.d/usr.sbin.mysqld
      - name: molecule
        uses: robertdebock/molecule-action@2.6.8
        with:
          image: ${{ matrix.config.image }}
          tag: ${{ matrix.config.tag }}
